// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class BankAccountDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bankAccountDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.BankAccountDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BankName("BankName"),
		AccountNumber("AccountNumber"),
		IFSCCode("IFSCCode"),
		HasDebitCard("HasDebitCard"),
		HasCreditcard("HasCreditcard"),
		IsEdiDetails("IsEdiDetails"),
		_ID("_ID"),
		BankAccountDetails_DebitCardDetails("NativeMobile.BankAccountDetails_DebitCardDetails"),
		BankAccountDetails_CreditCardDetails("NativeMobile.BankAccountDetails_CreditCardDetails"),
		BankAccountDetails_Bank("NativeMobile.BankAccountDetails_Bank");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BankAccountDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NativeMobile.BankAccountDetails"));
	}

	protected BankAccountDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bankAccountDetailsMendixObject)
	{
		if (bankAccountDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NativeMobile.BankAccountDetails", bankAccountDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NativeMobile.BankAccountDetails");

		this.bankAccountDetailsMendixObject = bankAccountDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BankAccountDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nativemobile.proxies.BankAccountDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nativemobile.proxies.BankAccountDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static nativemobile.proxies.BankAccountDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.BankAccountDetails(context, mendixObject);
	}

	public static nativemobile.proxies.BankAccountDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.BankAccountDetails.initialize(context, mendixObject);
	}

	public static java.util.List<nativemobile.proxies.BankAccountDetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<nativemobile.proxies.BankAccountDetails> result = new java.util.ArrayList<nativemobile.proxies.BankAccountDetails>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//NativeMobile.BankAccountDetails" + xpathConstraint))
			result.add(nativemobile.proxies.BankAccountDetails.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of BankName
	 */
	public final java.lang.String getBankName()
	{
		return getBankName(getContext());
	}

	/**
	 * @param context
	 * @return value of BankName
	 */
	public final java.lang.String getBankName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BankName.toString());
	}

	/**
	 * Set value of BankName
	 * @param bankname
	 */
	public final void setBankName(java.lang.String bankname)
	{
		setBankName(getContext(), bankname);
	}

	/**
	 * Set value of BankName
	 * @param context
	 * @param bankname
	 */
	public final void setBankName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bankname)
	{
		getMendixObject().setValue(context, MemberNames.BankName.toString(), bankname);
	}

	/**
	 * @return value of AccountNumber
	 */
	public final java.lang.Long getAccountNumber()
	{
		return getAccountNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountNumber
	 */
	public final java.lang.Long getAccountNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AccountNumber.toString());
	}

	/**
	 * Set value of AccountNumber
	 * @param accountnumber
	 */
	public final void setAccountNumber(java.lang.Long accountnumber)
	{
		setAccountNumber(getContext(), accountnumber);
	}

	/**
	 * Set value of AccountNumber
	 * @param context
	 * @param accountnumber
	 */
	public final void setAccountNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long accountnumber)
	{
		getMendixObject().setValue(context, MemberNames.AccountNumber.toString(), accountnumber);
	}

	/**
	 * @return value of IFSCCode
	 */
	public final java.lang.String getIFSCCode()
	{
		return getIFSCCode(getContext());
	}

	/**
	 * @param context
	 * @return value of IFSCCode
	 */
	public final java.lang.String getIFSCCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IFSCCode.toString());
	}

	/**
	 * Set value of IFSCCode
	 * @param ifsccode
	 */
	public final void setIFSCCode(java.lang.String ifsccode)
	{
		setIFSCCode(getContext(), ifsccode);
	}

	/**
	 * Set value of IFSCCode
	 * @param context
	 * @param ifsccode
	 */
	public final void setIFSCCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ifsccode)
	{
		getMendixObject().setValue(context, MemberNames.IFSCCode.toString(), ifsccode);
	}

	/**
	 * @return value of HasDebitCard
	 */
	public final java.lang.Boolean getHasDebitCard()
	{
		return getHasDebitCard(getContext());
	}

	/**
	 * @param context
	 * @return value of HasDebitCard
	 */
	public final java.lang.Boolean getHasDebitCard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasDebitCard.toString());
	}

	/**
	 * Set value of HasDebitCard
	 * @param hasdebitcard
	 */
	public final void setHasDebitCard(java.lang.Boolean hasdebitcard)
	{
		setHasDebitCard(getContext(), hasdebitcard);
	}

	/**
	 * Set value of HasDebitCard
	 * @param context
	 * @param hasdebitcard
	 */
	public final void setHasDebitCard(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasdebitcard)
	{
		getMendixObject().setValue(context, MemberNames.HasDebitCard.toString(), hasdebitcard);
	}

	/**
	 * @return value of HasCreditcard
	 */
	public final java.lang.Boolean getHasCreditcard()
	{
		return getHasCreditcard(getContext());
	}

	/**
	 * @param context
	 * @return value of HasCreditcard
	 */
	public final java.lang.Boolean getHasCreditcard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasCreditcard.toString());
	}

	/**
	 * Set value of HasCreditcard
	 * @param hascreditcard
	 */
	public final void setHasCreditcard(java.lang.Boolean hascreditcard)
	{
		setHasCreditcard(getContext(), hascreditcard);
	}

	/**
	 * Set value of HasCreditcard
	 * @param context
	 * @param hascreditcard
	 */
	public final void setHasCreditcard(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hascreditcard)
	{
		getMendixObject().setValue(context, MemberNames.HasCreditcard.toString(), hascreditcard);
	}

	/**
	 * @return value of IsEdiDetails
	 */
	public final java.lang.Boolean getIsEdiDetails()
	{
		return getIsEdiDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEdiDetails
	 */
	public final java.lang.Boolean getIsEdiDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEdiDetails.toString());
	}

	/**
	 * Set value of IsEdiDetails
	 * @param isedidetails
	 */
	public final void setIsEdiDetails(java.lang.Boolean isedidetails)
	{
		setIsEdiDetails(getContext(), isedidetails);
	}

	/**
	 * Set value of IsEdiDetails
	 * @param context
	 * @param isedidetails
	 */
	public final void setIsEdiDetails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isedidetails)
	{
		getMendixObject().setValue(context, MemberNames.IsEdiDetails.toString(), isedidetails);
	}

	/**
	 * @return value of _ID
	 */
	public final java.lang.Long get_ID()
	{
		return get_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of _ID
	 */
	public final java.lang.Long get_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames._ID.toString());
	}

	/**
	 * Set value of _ID
	 * @param _id
	 */
	public final void set_ID(java.lang.Long _id)
	{
		set_ID(getContext(), _id);
	}

	/**
	 * Set value of _ID
	 * @param context
	 * @param _id
	 */
	public final void set_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long _id)
	{
		getMendixObject().setValue(context, MemberNames._ID.toString(), _id);
	}

	/**
	 * @return value of BankAccountDetails_DebitCardDetails
	 */
	public final nativemobile.proxies.DebitCardDetails getBankAccountDetails_DebitCardDetails() throws com.mendix.core.CoreException
	{
		return getBankAccountDetails_DebitCardDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of BankAccountDetails_DebitCardDetails
	 */
	public final nativemobile.proxies.DebitCardDetails getBankAccountDetails_DebitCardDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nativemobile.proxies.DebitCardDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankAccountDetails_DebitCardDetails.toString());
		if (identifier != null)
			result = nativemobile.proxies.DebitCardDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BankAccountDetails_DebitCardDetails
	 * @param bankaccountdetails_debitcarddetails
	 */
	public final void setBankAccountDetails_DebitCardDetails(nativemobile.proxies.DebitCardDetails bankaccountdetails_debitcarddetails)
	{
		setBankAccountDetails_DebitCardDetails(getContext(), bankaccountdetails_debitcarddetails);
	}

	/**
	 * Set value of BankAccountDetails_DebitCardDetails
	 * @param context
	 * @param bankaccountdetails_debitcarddetails
	 */
	public final void setBankAccountDetails_DebitCardDetails(com.mendix.systemwideinterfaces.core.IContext context, nativemobile.proxies.DebitCardDetails bankaccountdetails_debitcarddetails)
	{
		if (bankaccountdetails_debitcarddetails == null)
			getMendixObject().setValue(context, MemberNames.BankAccountDetails_DebitCardDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BankAccountDetails_DebitCardDetails.toString(), bankaccountdetails_debitcarddetails.getMendixObject().getId());
	}

	/**
	 * @return value of BankAccountDetails_CreditCardDetails
	 */
	public final nativemobile.proxies.CreditCardDetails getBankAccountDetails_CreditCardDetails() throws com.mendix.core.CoreException
	{
		return getBankAccountDetails_CreditCardDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of BankAccountDetails_CreditCardDetails
	 */
	public final nativemobile.proxies.CreditCardDetails getBankAccountDetails_CreditCardDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nativemobile.proxies.CreditCardDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankAccountDetails_CreditCardDetails.toString());
		if (identifier != null)
			result = nativemobile.proxies.CreditCardDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BankAccountDetails_CreditCardDetails
	 * @param bankaccountdetails_creditcarddetails
	 */
	public final void setBankAccountDetails_CreditCardDetails(nativemobile.proxies.CreditCardDetails bankaccountdetails_creditcarddetails)
	{
		setBankAccountDetails_CreditCardDetails(getContext(), bankaccountdetails_creditcarddetails);
	}

	/**
	 * Set value of BankAccountDetails_CreditCardDetails
	 * @param context
	 * @param bankaccountdetails_creditcarddetails
	 */
	public final void setBankAccountDetails_CreditCardDetails(com.mendix.systemwideinterfaces.core.IContext context, nativemobile.proxies.CreditCardDetails bankaccountdetails_creditcarddetails)
	{
		if (bankaccountdetails_creditcarddetails == null)
			getMendixObject().setValue(context, MemberNames.BankAccountDetails_CreditCardDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BankAccountDetails_CreditCardDetails.toString(), bankaccountdetails_creditcarddetails.getMendixObject().getId());
	}

	/**
	 * @return value of BankAccountDetails_Bank
	 */
	public final nativemobile.proxies.Bank getBankAccountDetails_Bank() throws com.mendix.core.CoreException
	{
		return getBankAccountDetails_Bank(getContext());
	}

	/**
	 * @param context
	 * @return value of BankAccountDetails_Bank
	 */
	public final nativemobile.proxies.Bank getBankAccountDetails_Bank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nativemobile.proxies.Bank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankAccountDetails_Bank.toString());
		if (identifier != null)
			result = nativemobile.proxies.Bank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BankAccountDetails_Bank
	 * @param bankaccountdetails_bank
	 */
	public final void setBankAccountDetails_Bank(nativemobile.proxies.Bank bankaccountdetails_bank)
	{
		setBankAccountDetails_Bank(getContext(), bankaccountdetails_bank);
	}

	/**
	 * Set value of BankAccountDetails_Bank
	 * @param context
	 * @param bankaccountdetails_bank
	 */
	public final void setBankAccountDetails_Bank(com.mendix.systemwideinterfaces.core.IContext context, nativemobile.proxies.Bank bankaccountdetails_bank)
	{
		if (bankaccountdetails_bank == null)
			getMendixObject().setValue(context, MemberNames.BankAccountDetails_Bank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BankAccountDetails_Bank.toString(), bankaccountdetails_bank.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bankAccountDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.BankAccountDetails that = (nativemobile.proxies.BankAccountDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NativeMobile.BankAccountDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
