// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class BankBrach
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bankBrachMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.BankBrach";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BranchName("BranchName"),
		IFSCCode("IFSCCode"),
		BankBrach_Bank("NativeMobile.BankBrach_Bank");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BankBrach(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NativeMobile.BankBrach"));
	}

	protected BankBrach(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bankBrachMendixObject)
	{
		if (bankBrachMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NativeMobile.BankBrach", bankBrachMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NativeMobile.BankBrach");

		this.bankBrachMendixObject = bankBrachMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BankBrach.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nativemobile.proxies.BankBrach initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nativemobile.proxies.BankBrach.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static nativemobile.proxies.BankBrach initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.BankBrach(context, mendixObject);
	}

	public static nativemobile.proxies.BankBrach load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.BankBrach.initialize(context, mendixObject);
	}

	public static java.util.List<nativemobile.proxies.BankBrach> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<nativemobile.proxies.BankBrach> result = new java.util.ArrayList<nativemobile.proxies.BankBrach>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//NativeMobile.BankBrach" + xpathConstraint))
			result.add(nativemobile.proxies.BankBrach.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of BranchName
	 */
	public final java.lang.String getBranchName()
	{
		return getBranchName(getContext());
	}

	/**
	 * @param context
	 * @return value of BranchName
	 */
	public final java.lang.String getBranchName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BranchName.toString());
	}

	/**
	 * Set value of BranchName
	 * @param branchname
	 */
	public final void setBranchName(java.lang.String branchname)
	{
		setBranchName(getContext(), branchname);
	}

	/**
	 * Set value of BranchName
	 * @param context
	 * @param branchname
	 */
	public final void setBranchName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String branchname)
	{
		getMendixObject().setValue(context, MemberNames.BranchName.toString(), branchname);
	}

	/**
	 * @return value of IFSCCode
	 */
	public final java.lang.String getIFSCCode()
	{
		return getIFSCCode(getContext());
	}

	/**
	 * @param context
	 * @return value of IFSCCode
	 */
	public final java.lang.String getIFSCCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IFSCCode.toString());
	}

	/**
	 * Set value of IFSCCode
	 * @param ifsccode
	 */
	public final void setIFSCCode(java.lang.String ifsccode)
	{
		setIFSCCode(getContext(), ifsccode);
	}

	/**
	 * Set value of IFSCCode
	 * @param context
	 * @param ifsccode
	 */
	public final void setIFSCCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ifsccode)
	{
		getMendixObject().setValue(context, MemberNames.IFSCCode.toString(), ifsccode);
	}

	/**
	 * @return value of BankBrach_Bank
	 */
	public final nativemobile.proxies.Bank getBankBrach_Bank() throws com.mendix.core.CoreException
	{
		return getBankBrach_Bank(getContext());
	}

	/**
	 * @param context
	 * @return value of BankBrach_Bank
	 */
	public final nativemobile.proxies.Bank getBankBrach_Bank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nativemobile.proxies.Bank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankBrach_Bank.toString());
		if (identifier != null)
			result = nativemobile.proxies.Bank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BankBrach_Bank
	 * @param bankbrach_bank
	 */
	public final void setBankBrach_Bank(nativemobile.proxies.Bank bankbrach_bank)
	{
		setBankBrach_Bank(getContext(), bankbrach_bank);
	}

	/**
	 * Set value of BankBrach_Bank
	 * @param context
	 * @param bankbrach_bank
	 */
	public final void setBankBrach_Bank(com.mendix.systemwideinterfaces.core.IContext context, nativemobile.proxies.Bank bankbrach_bank)
	{
		if (bankbrach_bank == null)
			getMendixObject().setValue(context, MemberNames.BankBrach_Bank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BankBrach_Bank.toString(), bankbrach_bank.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bankBrachMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.BankBrach that = (nativemobile.proxies.BankBrach) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NativeMobile.BankBrach";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
